# Generated by Django 3.2.4 on 2021-06-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0002_auto_20210610_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pic',
            field=models.ImageField(blank=True, upload_to='shirt_pic'),
        ),
    ]
