# Generated by Django 3.2.4 on 2021-06-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0004_item_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
