# Generated by Django 3.2.4 on 2021-06-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eCom', '0015_auto_20210618_0120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='eCom.OrderItem'),
        ),
    ]
